# SPDX-License-Identifier: AGPL-3.0-or-later
---
namespace: leegarrett
name: network
version: 0.1.0
readme: README.md
authors:
  - Lee Garrett <lgarrett@rocketjump.eu>
description: Collection of network-related roles on Linux
license:
  - AGPL-3.0-or-later
tags:
  - network
repository: https://github.com/leegarrett/ansible_collection/
issues: https://github.com/leegarrett/ansible_collection/issues
